### PR TITLE
xorg-xf86-video-amdgpu 19.0.1

### PR DESCRIPTION
**Pull request by Minzords**

### CODE REVIEW

**Comment by tnut** [comment]
Adjust the makedepends variable

**Comment by Minzords** [comment]
Done :)

**Comment by Minzords** [comment]
If it's don't work update to mesa 19.1.1. :) My system has mesa in version 19.0.4 :+1: .

**Comment by tnut** [comment]
will be committed soon (with another approx coming 150 commits)

**Pull request closed without merging**
